site_name: "Data Structures in Java"
site_author: "John Foley <johnf@middlebury.edu>"
site_description: "Content created for remote learning of CSC212: Data Structures in Spring 2020 at Smith College."
docs_dir: "src"
use_directory_urls: false
repo_url: "https://github.com/jjfiv/ds4j"
repo_name: "Github"
edit_uri: "tree/master/src/"
theme: 
    name: "readthedocs"
    custom_dir: "customize"
nav:
    - 'About': 'README.md'
    - 'Array-Based Lists: FixedSizeList & GrowableList (aka ArrayList)': 'FSL.md'
    - 'Singly Linked-Lists': 'SLL.md'
    - 'Doubly Linked-Lists': 'DLL.md'
    - 'Chunky ArrayLists': 'ChunkyArrayList.md'
    - 'Lists Conclusions': 'Lists.md'
    - 'Sorting (Part 1): Binary Search, IsSorted, BubbleSort': 'Sorting1.md'
    - 'Sorting (Part 2): Insertion, Selection and Merge Sort': 'Sorting2.md'
    - 'Intro to Trees': 'Trees.md'
    - 'Hashing, HashTables, HashSets, and HashMaps': 'HashTables.md'
    - 'QuickSort': 'QuickSort.md'
    - 'Heaps & HeapSort': 'Heaps.md'
    - 'Balancing Tree Algorithms': 'Balancing.md'
    - 'Intro to Graphs & Graph Algorithms': 'Graphs.md'
