site_name: "Data Structures in Java"
site_author: "John Foley <johnf@middlebury.edu>"
site_description: "Content created for remote learning of CSC212: Data Structures in Spring 2020 at Smith College."
docs_dir: "src"
use_directory_urls: false
repo_url: "https://github.com/jjfiv/ds4j"
repo_name: "Github"
edit_uri: "tree/master/src/"
theme: 
    name: "readthedocs"
    custom_dir: "customize"
markdown_extensions:
    - extra
    - md_in_html
    - sane_lists
    - tables
    - nl2br
    - mdx_math
nav:
    - '📖 About': 'README.md'
    - '📖 Java from Python': 'java-from-python.md'
    - '📖 Classes & Objects': 'objects-101.md'
    - '📖 Using Lists': 'list-methods.md'
    - '📖 Stacks & Queues': 'stacks-and-queues.md'
    - '📖 Complexity': 'complexity.md'
    - '📺 Array-Based Lists': 'FSL.md'
    - '📺 Singly Linked-Lists': 'SLL.md'
    - '📺 Doubly Linked-Lists': 'DLL.md'
    - '📺 Chunky ArrayLists': 'ChunkyArrayList.md'
    - '📺 Lists Conclusions': 'Lists.md'
    - '📺 Sorting (1/2): Binary Search, IsSorted, BubbleSort': 'Sorting1.md'
    - '📺 Sorting (2/2): Insertion, Selection and Merge Sort': 'Sorting2.md'
    - '📖Aside: Comparison': 'comparison.md'
    - '📺 Intro to Trees': 'Trees.md'
    - '📺 Hashing & HashTables': 'HashTables.md'
    - '📺 QuickSort': 'QuickSort.md'
    - '📺 Heaps & HeapSort': 'Heaps.md'
    - '📺 Balancing Tree Algorithms': 'Balancing.md'
    - '📺 Intro to Graphs & Graph Algorithms': 'Graphs.md'
